Fix datasets
Signed-off-by: Lucas Hagen <lucas_hagen@hotmail.com>

diff --git a/traces/merge_all b/traces/merge_all
--- a/traces/merge_all
+++ b/traces/merge_all
@@ -4,57 +4,102 @@ SCRIPT_PATH=`realpath $0`
 SCRIPT_NAME=`basename $SCRIPT_PATH`
 SCRIPT_DIR=`dirname $SCRIPT_PATH`
 
-FILES_DIR="$SCRIPT_DIR/to_merge"
+FILES_DIR="$SCRIPT_DIR/attacks"
+
+BUILD_FOLDER="$SCRIPT_DIR/build"
+mkdir -p $BUILD_FOLDER
 
 GZ_EQUINIX_FILE="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon.pcap.gz"
+EQUINIX_FILE="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon.pcap"
+TRACE_PART="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon_00003_20160406100730.pcap"
+
 GZ_EQUINIX_FILE_SHA256="72440cb663607a735d3eccee30d65d94b34a83f7b1be7a18ab63ae32ea617503"
 
-EQUINIX_FILE="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon.pcap"
-EQUINIX_FILE_SHA256="3c4493fe28182288249f550e950018f7be33c735183e79dfe43bef84d38efafb"
+GENUINE_FILE="$SCRIPT_DIR/dataset_genuine.pcap"
 
-TRACE_PART="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon_00003_20160406100730.pcap"
-TRACE_PART_SHA256="95f28aed67136b86ec0ae0396af36fddca6f118f0ebe3ff32ce42e8dd42781bc"
-
-ATTACKS_FILE="$SCRIPT_DIR/attacks.pcapng"
+ATTACKS_FILE="$SCRIPT_DIR/dataset_attacks.pcap"
 ATTACKS_FILE_SHA256="6152de9fd1aea102c6aa8a30a123f3b1afa70a386a8d35fab7b237713eedd7de"
 
-OUTPUT_FILE="$SCRIPT_DIR/full_dataset.pcapng"
-OUTPUT_FILE_SHA256="0f8366f294852808b5f0cd1c460e1896c10c7e33b12e13962231962fbfac351d"
+OUTPUT_FILE="$SCRIPT_DIR/dataset_full.pcap"
+OUTPUT_FILE_SHA256="c356a5e98ddb053df27688f031868bba7806ca65233e96be928ea1e54b3995a2"
+
+if [ "$1" = "override" ] | [ "$1" = "-o" ] | [ "$1" = "--override" ] ; then
+    OVERRIDE=true
+else
+    OVERRIDE=false
+fi
 
 echo "Generating complete dataset at '$OUTPUT_FILE'"
+echo ""
 
-if [ ! $(sha256sum $GZ_EQUINIX_FILE | awk '{print $1}') = "$GZ_EQUINIX_FILE_SHA256" ] ; then
-    echo "Error: sha256sum mismatch for '$GZ_EQUINIX_FILE'"
-    exit 1
+# ==============================================================================
+# BUILD GENUINE
+# ==============================================================================
+
+if $OVERRIDE || [ ! -f "$GENUINE_FILE" ] ; then
+    echo "[1] Building 'genuine' dataset"
+
+    echo "    - Verifying checksum"
+    if [ ! $(sha256sum $GZ_EQUINIX_FILE | awk '{print $1}') = "$GZ_EQUINIX_FILE_SHA256" ] ; then
+        echo ""
+        echo "Error: sha256sum mismatch for '$GZ_EQUINIX_FILE'"
+        exit 1
+    fi
+
+    if $OVERRIDE || [ ! -f "$EQUINIX_FILE" ] ; then
+        echo "    - Decompressing equinix file"
+        gunzip -c $GZ_EQUINIX_FILE > $EQUINIX_FILE
+    fi
+
+    if $OVERRIDE || [ ! -f "$TRACE_PART" ] ; then
+        echo "    - Splitting equinix file into 10s windows"
+        editcap -i 10 $EQUINIX_FILE $EQUINIX_FILE
+    fi
+
+    if $OVERRIDE || [ ! -f "$BUILD_FOLDER/genuine.pcapng" ] ; then
+        echo "    - Formating genuine dataset"
+        editcap -T ether -s 65535 $TRACE_PART $BUILD_FOLDER/genuine.pcapng
+    fi
+
+    echo "    - Converting to pcap"
+    tshark -F pcap -r $BUILD_FOLDER/genuine.pcapng -w $GENUINE_FILE
+
 else
-    echo "Equinix/CAIDA file sha256sum matches!"
+    echo "[1] Building genuine dataset                                [SKIPPED]"
 fi
 
-echo "Decompressing equinix file"
+# ==============================================================================
+# BUILD ATTACKS
+# ==============================================================================
 
-gunzip -c $GZ_EQUINIX_FILE > $EQUINIX_FILE
-
-echo "Splitting equinix file into 10 seconds window"
-
-editcap -i 10 $EQUINIX_FILE $EQUINIX_FILE
-
-echo "Merging all attack pcaps"
-
-mergecap -w $ATTACKS_FILE $FILES_DIR/*.pcapng
-
-if [ ! $(sha256sum $ATTACKS_FILE | awk '{print $1}') = "$ATTACKS_FILE_SHA256" ] ; then
-    echo "Error: sha256sum mismatch for '$ATTACKS_FILE'"
-    exit 1
+if $OVERRIDE || [ ! -f "$ATTACKS_FILE" ] ; then
+    echo "[3] Building 'attacks' dataset"
+    mergecap -w $BUILD_FOLDER/attacks.pcapng $FILES_DIR/*.pcapng $FILES_DIR/*.pcap
+    tshark -s 65535 -F pcap -r $BUILD_FOLDER/attacks.pcapng -w $ATTACKS_FILE
+else
+    echo "[3] Building 'attacks' dataset                              [SKIPPED]"
 fi
 
-echo "Merging attacks with equinix (10s window) file"
+# ==============================================================================
+# BUILD FULL
+# ==============================================================================
 
-mergecap -w $OUTPUT_FILE $TRACE_PART $ATTACKS_FILE
+if $OVERRIDE || [ ! -f "$OUTPUT_FILE" ] ; then
+    echo "[4] Building 'full' dataset"
+    mergecap -w $BUILD_FOLDER/full.pcapng $GENUINE_FILE $ATTACKS_FILE
+    echo "    Converting to pcap"
+    tshark -F pcap -r $BUILD_FOLDER/full.pcapng -w $OUTPUT_FILE
+else
+    echo "[4] Building 'full' dataset                                 [SKIPPED]"
+fi
 
+echo "    Verifying 'full' dataset..."
 if [ ! $(sha256sum $OUTPUT_FILE | awk '{print $1}') = "$OUTPUT_FILE_SHA256" ] ; then
+    echo ""
     echo "Error: sha256sum mismatch for '$OUTPUT_FILE'"
     exit 1
 fi
 
-
-echo "Done! Saved as: $OUTPUT_FILE"
+echo ""
+echo "Output file: $OUTPUT_FILE"
+echo "Done!"
